import { Calendar } from './styles/style'

const Index = () => {
    return <>
        <Calendar>
             <tr>
                <th>星期日</th>
                <th>星期一</th>
                <th>星期二</th>
                <th>星期三</th>
                <th>星期四</th>
                <th>星期五</th>
                <th>星期六</th>
            </tr>
            <tr>
                <td className="no-style"></td>
                <td>
                    <span>1</span>
                </td>
                <td>
                    <span>2</span>
                </td>
                <td>
                    <span>3</span>
                </td>
                <td>
                    <span>4</span>
                </td>
                <td>
                    <span>5</span>
                </td>
                <td>
                    <span>6</span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>7</span>
                </td>
                <td>
                    <span>8</span>
                </td>
                <td>
                    <span>9</span>
                </td>
                <td>
                    <span>10</span>
                </td>
                <td>
                    <span>11</span>
                </td>
                <td>
                    <span>12</span>
                </td>
                <td>
                    <span>13</span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>14</span>
                </td>
                <td>
                    <span>15</span>
                </td>
                <td>
                    <span>16</span>
                </td>
                <td>
                    <span>17</span>
                </td>
                <td>
                    <span>18</span>
                </td>
                <td>
                    <span>19</span>
                </td>
                <td>
                    <span>20</span>
                </td>
            </tr>
            <tr>
                <td>
                    <span>21</span>
                </td>
                <td>
                    <span>22</span>
                </td>
                <td>
                    <span>23</span>
                </td>
                <td>
                    <span>24</span>
                </td>
                <td>
                    <span>25</span>
                </td>
                <td>
                    <span>26</span>
                </td>
                <td>
                    <span>27</span>
                </td>
            </tr>
            <tr>
            <td>
                    <span>28</span>
                </td>
                <td>
                    <span>29</span>
                </td>
                <td>
                    <span>30</span>
                </td>
                <td>
                    <span>31</span>
                </td>
                <td className="no-style"></td>
                <td className="no-style"></td>
                <td className="no-style"></td>
            </tr>
        </Calendar>
    </>
}

export default Index